name: CI

on:
  push:
    branches:
      - archive_3_x
  pull_request:
    branches:
      - archive_3_x

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ 17 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: adopt-hotspot
          java-version: ${{ matrix.java-version }}

      - run: ./gradlew --info build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-libs
          retention-days: 21
          path: |
            build/libs/

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Event File
          retention-days: 21
          path: |
            **/TEST-*
            **/hs_err_pid*

  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Event File
          path: ${{ github.event_path }}
